DROP DATABASE IF EXISTS groupomania;
CREATE DATABASE groupomania;
USE groupomania;
SET NAMES 'utf8';

CREATE TABLE users (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
birthdate DATE NOT NULL,
gender VARCHAR(6) NOT NULL,
imageUrl VARCHAR(255) NOT NULL,
deleted BOOLEAN,
moderator BOOLEAN,
PRIMARY KEY (id),
CONSTRAINT UC_User UNIQUE (id, email)
)
ENGINE=INNODB;

CREATE TABLE publications (
id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
text TEXT NOT NULL,
autorId SMALLINT UNSIGNED NOT NULL,
imageUrl VARCHAR(255) NOT NULL,
usersLiked TEXT,
likes SMALLINT NOT NULL,
comments SMALLINT UNSIGNED,
date_insertion DATETIME,
date_modification DATETIME,
moderationIntervention BOOLEAN,
PRIMARY KEY (id),
UNIQUE (id)
)
ENGINE=INNODB;

CREATE TABLE comments (
id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
text TEXT NOT NULL,
autorId SMALLINT UNSIGNED NOT NULL,
pubOriginId MEDIUMINT UNSIGNED NOT NULL,
date_insertion DATETIME,
date_modification DATETIME,
moderationIntervention BOOLEAN,
PRIMARY KEY (id),
UNIQUE (id)
)
ENGINE=INNODB;



